### ISSUE TITLE
Disable GA parallelism

### ISSUE THREAD

**Issue by keegit** [innoave/genevo#24]
I'm currently implementing a genetic algorithm that runs a circuit simulation to evaluate a circuits fitness. To perform the simulation, I use a third party C API. This API is called from within the `fitness_of()` function of the `FitnessFunction` trait I defined.

The third party C API I use _cannot_ be used in a multi-threaded fashion. so I'm wondering if it's possible to disable the parallelism in the `ga` module; or if there is a less performant, sequential version of genevo.

**Comment by haraldmaida** [comment]
since Version 0.7 of genevo it should be easy to disable parallel execution. In fact it is already disabled for wasm targets due to issues on that platform. I will expose a feature flag. In the meantime you could try to disable it in a fork of genevo. In Cargo.toml

replace: 
```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1"
```
with:
```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = {version = "1", optional = true }
```

I'm currently not at my home computer to test it. So I'm not sure if this really works.
